#!/usr/bin/sh

# id=$(rfkill | awk '/bluetooth/{print $1}')

# rfkill event |
  # stdbuf -o0 awk -v idx="$id" '$0 ~ "idx " idx {print $10}'


getData (){
  bluetoothctl show | awk -F": " '/Powered/{print $2}'
}

gdbus monitor --system \
  --dest org.bluez \
  --object-path /org/bluez/hci0 | \
  while read -r line;
  do 
    getData
  done
