#!/usr/bin/env bash

getData (){
  defref=$(pactl get-default-source)
  output='['
  for source in $(pactl list short sources | awk '{print $2}')
  do 
    read -r id icon name <<< "$(pactl --format=json list sources | jq -r '.[] | select(.name=="'"$source"'") | [.properties["object.id"], .properties["device.icon_name"], .properties["device.description"]] | @tsv')" 
    ismute=$(pactl get-source-mute "$source" | awk '{print $2}')
    volume=$(wpctl get-volume "$id" | awk '{print $2*100}')
    [ "$defref" = "$source" ] && default=true || default=false
    output=$output'{"id": '$id', "mute": "'$ismute'", "volume": '$volume', "default": '$default', "source": "'$source'", "name": "'$name'", "icon": "'$icon'"},'
  done
  echo "${output%?}]"
}

getData
pactl subscribe | while read -r line; do
    if echo "$line" | grep " on source " > /dev/null; then
        getData
    fi
done
