#!/usr/bin/sh

device=$(gdbus call --system \
  --dest org.freedesktop.NetworkManager \
  --object-path /org/freedesktop/NetworkManager \
  --method org.freedesktop.NetworkManager.GetDeviceByIpIface \
  'wlan0' | \
  awk -F"'" '{print $2}' )
### FIXME If the wlan is brought up after the initial load of script then there are no 
### AccessPoints in operation resulting in a null or "" return from below
getAP (){
  AP=$(gdbus call --system \
    --dest org.freedesktop.NetworkManager \
    --object-path "$device" \
    --method org.freedesktop.NetworkManager.Device.Wireless.GetAccessPoints | \
    awk -F"'" '{print $2}')
}

getData (){
  printf '%i\n' $(gdbus call --system \
    --dest org.freedesktop.NetworkManager \
    --object-path "$AP" \
    --method org.freedesktop.DBus.Properties.Get \
    "org.freedesktop.NetworkManager.AccessPoint" "Strength" | \
    awk -F" |>" '{print $2}')
}

getAP
# while [ -z "$AP" ]; 
#do
#  gdbus monitor --system \
#    --dest org.freedesktop.NetworkManager \
#    --object-path "$device" \
#    org.freedesktop.NetworkManager.Device.Wireless.GetAccessPoints | \
#    while read -r line ; 
#    do 
#      getAP
#      if [ -n "$AP" ]; then
#        break 2
#      fi
#    done
#done

gdbus monitor --system \
  --dest org.freedesktop.NetworkManager \
  --object-path $AP | \
  while read -r line;
  do 
    getData
  done
